import type { Metadata } from "next";
import "./globals.css";
import Image from "next/image";
import Nav from "./components/nav";
import ImgText from "./components/imgText";




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header className="flex justify-between items-center bg-black text-white font-bold  p-4">
          <ImgText src="/vercel.svg"  href="/" >Home</ImgText>
          <Nav link="/posts" >Posts</Nav>
          <Nav link="/icon" >Icon</Nav>
          <ImgText src="/window.svg"  href="/dashbord" >Dasbord</ImgText>
        </header>
        {children}
      </body>
    </html>
  );
}
